---
# vars file for roles/monitoring

graylog_host: "127.0.0.1"
beats_port: "5044"
metricbeat_log: "/var/log/metricbeat"

#DIR_MONITORING: "/opt/monitoring"
metricbeat_config_path: "/etc/metricbeat/metricbeat.yml"
#metricbeat_rpm: metricbeat-7.12.0-x86_64.rpm
metricbeat_is_local: true     # true = Metricbeat на том же хосте → 5044 НЕ открываем
