graylog_host: "127.0.0.1"
external_ip: "88.214.34.49"

graylog_api_url: "https://{{ external_ip }}/api"

local_repo_dir: "{{ playbook_dir }}/roles/graylog_offline_install/files"

metricbeat_log: "/var/log/metricbeat"
beats_port: "5044"