# roles/monitoring/tasks/search.yml
- name: Create Metricbeat search
  uri:
    url: "{{ graylog_api_url }}/views/search"
    method: POST
    user: "{{ graylog_root_user }}"
    password: "{{ graylog_root_password }}"
    force_basic_auth: true
    validate_certs: false
    headers:
      X-Requested-By: ansible
      Content-Type: application/json
    body_format: json
    body:
      queries:
        - id: metricbeat-query
          query:
            type: elasticsearch
            query_string: "*"
          timerange:
            type: relative
            from: 300
          filter:
            type: stream
            id: "{{ metricbeat_stream_id }}"
          search_types:
            - id: cpu-search-type
              type: messages
              name: Metricbeat Messages
              limit: 1
            - id: memory-search-type
              type: messages
              name: Metricbeat Messages
              limit: 1
            - id: disk-search-type
              type: messages
              name: Metricbeat Messages
              limit: 1
            - id: network-search-type
              type: messages
              name: Metricbeat Messages
              limit: 1
            - id: la1-search-type
              type: messages
              name: Metricbeat Messages
              limit: 1
            - id: la5-search-type
              type: messages
              name: Metricbeat Messages
              limit: 1
            - id: la15-search-type
              type: messages
              name: Metricbeat Messages
              limit: 1
    status_code: 201
  register: metricbeat_search

- name: Set search_id fact
  set_fact:
    metricbeat_search_id: "{{ metricbeat_search.json.id }}"
