---
# Установка зависимостей через DNF или локально

#- name: Install dependencies
#  yum:
#    name: "{{ packages }}"
#    state: present

- name: Install local dependency rpms
  shell: |
    dnf install -y \
      glibc-2.28-13.el7.i686.rpm \
      libselinux-2.9-3.el7.3.i686.rpm \
      libsepol-2.9-1.el7.i686.rpm \
      zlib-1.2.11-18.el7.i686.rpm \
      openssl-libs-1.1.1w-4.el7.i686.rpm \
      openssl-pkcs11-0.4.11-2.el7.i686.rpm \
      libverto-0.3.2-1.el7.i686.rpm \
      krb5-libs-1.20.1-4.el7.i686.rpm \
      keyutils-libs-1.6-1.el7.i686.rpm \
      libcom_err-1.46.3-1.el7.3.i686.rpm \
      pcre2-10.46-1.el7.i686.rpm \
      --disablerepo="*"
  args:
    chdir: "{{ role_path }}/files"

