---
# Установка зависимостей через DNF или локально

- name: Install base system packages
  become: true
  dnf:
    name: "{{ packages }}"
    state: present
    disablerepo: "*"
    enablerepo: "graylog-offline"

