---
- name: UNInstall graylog server
  include_tasks: del_graylog.yml

- name: Uninstall mongodb
  include_tasks: del_mongodb.yml

- name: UNInstall elasticsearch
  include_tasks: del_elasticsearch.yml
