---
- name: UnInstall graylog server
  include_tasks: uninstall/del_graylog.yml

- name: Uninstall mongodb
  include_tasks: uninstall/del_mongodb.yml

- name: UnInstall elasticsearch
  include_tasks: uninstall/del_elasticsearch.yml
