---

#- name: UNInstall del_grayserver
#  include_tasks: del_grayserver.yml

- name: UNInstall del_opensearh.yml
  include_tasks: del_opensearh.yml

- name: Uninstall mongodb
  include_tasks: del_mongodb.yml